* 徐爱录--心即是理
** 1.徐爱引言
** 2.亲民与新民
** 3.至善是心之本体
   至善是属于内心本体的,而不是在外物上.
** 4.求孝道于内
   事父不是从父亲那里求得孝的道理.事君不是从君主那里求得忠的道理. 交友 、治理百姓,不是从朋
友和百姓那里求得信和任的道理.
   心即理.以没有私欲的心,去做任何事都是天理. 事父则孝,事君则忠,交友则信,治民则仁.
   细节上要分清主次,在自己心中去私欲,存天理的前提下去讲求.就怕有私心杂念去做.如果己心没有
私欲,冬天自然会想到为父母防寒;夏天自然会想到为父母消暑,有了心才有了根本.
   要做什么事情,首先要培养自己想要做的心.然后才可以不带私欲去做,才能顺应天理去把事情给做好
来.而不是在事物表面上一直纠结.
** 5.此心纯乎天理之极
   心到了,物自然会到.
** 6.知行合一
   指导孝父敬兄的道理,行动上却不能孝敬.
   这种情况是已被私欲隔断.行动上不能孝敬,那么压根就不知道孝父敬兄的道理.知行是不分开的,所以
不管什么大道理,光学不习是没用的,该干嘛干嘛.不要用自己知道的不够多为理由当借口而不去做.
** 7.行是知的功夫
   古人为什么把知行拆开?
   有一种人,稀里糊涂地去做,全然不理解做的原因和道理.所以才劝诫他认知的重要.
   还有一种人,异想天开,只会空想,全然不肯亲自行动,也只是靠主观猜测.所以必须跟他讲行的道理,才
可以知的正确.
   不要做第一种人,稀里糊涂地做.也不要做第二种人,只会空想.要知行合一.不能知行合一,还不如不做,
不知.
** 8.格物致知,止于至善
   什么是功?到达目的的途径便是功.
   精是一的功,博是约的功.
   格物致知,前后因果关系颠倒了,应该是先致知才能格物.
** 9.尽心即是尽性
   尽心就是尽性.不应该把心和性分开来说,如果要分开说,说明还没有尽心.
   事天,就是还没有与天合二为一.所以要继续修炼本心,去除这种念头.
** 10.身之主宰便是心
   身的主宰就是心了.心触发了就是意,意就是知,意之所在便是物.
   意在事亲上,那么事亲就是一物;意在事君上,那么事君便是一物;意在仁民爱物上,仁民爱屋便是一物.
   所以美欧心外之理,没有心外之物.
** 11.去其心之不正
   要时时去除不正心术,保全本体的纯正.
** 12.知是心之本体
   良知不需要借助外界去求得,但是一般人私心阻碍,所以需要用致知和格物的功夫,战胜私心恢复天理.
** 13.礼即是理
   用礼的精神来约束人的思想达到与天理的统一
** 14.天理人欲不并立
   只有一个心,没有夹杂人为因素的称道心,夹杂了称人心.
** 15.虚文胜而实行衰
   不要虚假做学问,而没有落到实处.
** 16.务本尚实,返朴还淳
   课本上删减罪恶,是为了减少乱象,引人向善.
   如果详细描写恶行,那么就会助长乱想,引导奸恶.
** 17.因时致治
   现代的人要用现代的方法去治理社会,因为环境已经发生了改变.
** 18.事即道,道即事
   事情就是道理,道理就是事情.
   史就是道:
   善用来教化,保存善的事迹让人仿效;
   恶作为戒条,保存戒条删去具体的恶行,来杜绝奸邪之人模仿.
** 19.孔子删<诗经>
** 20.徐爱跋
   先生说:格物是诚意的功夫,明善是城身的功夫,穷理是尽性的功夫,道问学是尊德性的功夫
* 陆澄录--格物无动静之分
** 1.主一之功  
   什么算是专注的功夫?读书一心在读书上用功夫,接客就一心在接客上用功夫,能否称为专注?
   贪色一心在美色上,贪财一心在财物上.这叫逐物,不叫专注.
** 2.念念存天理
   怎样立志?
   念念不忘存理想便是立志.
   如果白天做功夫觉得太过纷扰,就静坐;觉得不愿去看书,就要去看书,也是对症下药地修炼自己.
** 3.相下得益,相上招损
   与朋友相处,务必谦虚甘拜下风,就能得到益处;相互争高低就会带来损失.
   有位朋友谈了他近来的功夫,请先生指正.孟源在旁边说:"这事正是我以前最在行的"
   先生说:你的毛病又犯了.
   人生中最大的缺点.比如在一块地里种一颗大树,平时雨露的滋养,土地上的肥料都用来滋养这颗
树了.想要种些有用的谷物,必须砍去这颗树,连须根也不留下,这样才能种植谷物.否则,任凭耕耘培
土,也只是在滋养这个树根.
   我最大的缺点:一听到别人的指责就会恼怒.比如连根去除这颗大树.才能种植有用的谷物.
** 4.人心天理浑然
   人的精神风貌,谈吐举止,本来就不能完全通过文字来传达的.
** 5.心如明镜
   圣人的光辉事业,遇到恰当的时机才有这样的事情发生.
   如果心镜不明,时机来了就不能反照出来.
   学习,要让自己的心明亮如镜,就不怕明镜一样的心不能穷尽事物的变化.
** 6.义理无定在,无穷尽
** 7.人须在事上磨
   事情想的好好的,实际上遇到事情,就不能按这种思路去做.
   这是只静心修养,没有下克己功夫.只有在事情上磨练自己,才能立足.
** 8.下学与上达
   具体信息属于下学,抽象信息属于上达.
   求学的人只需从下学上用功,自然可以上达,不必另外寻找上达的功夫.
** 9.唯精唯一
   唯一:要让米干净洁白,目的
   唯精:筛拣
** 10.知行不分
** 11.以遵理为生
   只靠宁静来修炼,那么就会喜静厌动,会隐藏许多缺点不能除去.
   真正的功夫:静时不忘去人欲,存天理,动时不忘去人欲,存天理.那么就能获得真正的宁静.
** 12.三子是有意必
   处在夷狄的位置,就做夷狄该做的事.处在患难的处境,就做患难当做的事.
** 13.志与功
   学习比如从基础上下功夫,循序渐进,才能有进步.不要看到别人无所不知,无所不能,于是就想要在
刚开始学会所有的学问,哪有这种道理.
   立志用功,如同种树.刚开始只有根芽还没长出树干来,等长出树干还没长枝,长了树枝之后长叶子,
叶子长好后开花,结果.刚种上树根时,只管培土灌溉,不要想着生枝,长叶,开花,结果.空想那些有什么
用?只要不忘了培土灌溉的功夫,何愁没有枝叶和花果?
** 14.心即性,性即理
   看书看不明白?
   想学明白,必须得从自己得内心去用功,凡是不明白的,解释不通,就换位思考,从自己的内心体会,就
一定能学明白,解释得通畅.
** 15.理不容分析
   天理不容分析,精一已经把做学问的事说尽了.
** 16.反省慎独
   如何应对人情事变?
   关键在于致中和,致中和要靠慎独的功夫来修炼.
** 17.性,理关系
   仁义礼智都是心的不同表现而已,就好比,父亲叫我儿子.儿子叫我爸爸.
** 18.省察与克治
   先静坐,安定思绪.
   心能安定的时候,不能只教悬空静处.必须教他反省自察克己修身.
   这种功夫不能间断,好比彻底清除盗贼的决心.
   无事时,把好色,贪财,慕名等私欲统统搜寻出来,拔去病根,让它们永不再起.就像猫捉老鼠,眼睛盯着,耳
朵听着,才有一丝萌动,就立刻去掉,态度坚决,不能姑息迁就,不能窝藏它,不能放它生路,这才是真正的功夫,
如此才能扫尽心中的私欲.等到心中没有私欲可除,能做到端身拱手.
   孔子说:天下的事有什么可思考和忧虑的?但这不是初学时可以理解的.
   初学时必须想着内省自察克制私欲.只思一个天理,等到天理完全纯正时,就是何思何虑的境界了.
** 19.非鬼迷,心自迷
   没有什么鬼,都是自己的心作怪.
   人好色,就是色鬼迷.
   贪财,就是贪财鬼迷.
   不该怒而怒,就是怒鬼迷.
   不该怕而怕,就是惧鬼迷.
** 20.定是心之本体
   定是心之本体.所谓动与静只是天理在不同时间环境的表示.
** 21.孔子正名
   孔子替子从政,感化了子.子泣迎父,让位于父.父不愿意接受.子再上报天子让位于天子和诸侯.父说子已
有美德.子不得不奉其为太公,做回了君王.名正言顺.
** 22.毁不灭性
   陆澄知儿子病危,万分忧愁,不能忍受.
   这时候该修身养性,如果放过这个机会,平时学习有什么用?人就是要在艰难时刻才能得到意志的磨练.父
亲关爱儿子,是最自然的.但是天理也有个中正适度,超过限度就是私欲.
   人们认为天理应当是忧戚状,一味悲怆起来,而不知道七情六欲一旦发作,往往是过分的多,很少有不及的.
过分了就不是本心,必须调节到适中才行.
** 23.有是体即有是用
   有'情感未发时的中正',就有'情感发出来符合中正的平和'.现在人没有做到'感情发出来符合中正的平和
',是因为'感情未发时的中正状态'还没能完全做到.
** 24.阳明与易经
   初九潜龙勿用:卦象是早晨,其变化是遇到白天,占扑用的是卦辞和 x 辞.
** 25.存养夜气
   夜气是对普通的人说的.
   对于求学的人无论日间有事无事,都能在本心修养功夫.
** 26.动静无端
   出入无时,莫知其乡:出入没有固定时间,也不知道方向.
   求学的人也要知道本心就是这样的.
   不能随便说:善念出就是天理亡,善念入就是天理存.本心是无出无入的.心的出入也只是动和静,动静是
没有方向的.
** 27."道"无所谓上下
   道不分上下.
   在道上,仁者见仁,智者见智.普通人知道怎么做,却讲不出其中的道理出来,所以也就不知道怎么做君子了.
   仁和智认知片面了,就会变成邪说.
   但是无论用什么方式占卜都是<易>
** 28.仁者恻隐心怀
** 29.权变之道
   执中无权犹执一
   中就是天理,是变化的.天理随着时间的变化而变化的.想着怎么将其中道理讲得完美无缺,事先确定规范放
在前面,这样做恰恰是偏执.
   做事情要顺应天理,应势力导.
** 30.自愿原则
   善念存在心中,就是天理.意念是善的,就不用去想其它的善.意念是善的,那么就没有恶.
   所以,立志的人只要永远确认善念就可以了.
